### ISSUE TITLE
Generated SQL Tab UI Enhancement

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#101]
**Summary**
Change the "Generated SQL" tab to Preview | Run | Save

**Please describe the problem you are trying to solve.**
Generate SQL, to me, means "write out the SQL".
Save SQL, to me, means "save the SQL for later".
Neither of them, to me, mean "execute the SQL on a database I'm going to tell you about".

**Proposed Solution**
I'd love to see three buttons here:
1. Preview SQL
2. Run SQL
3. Save SQL

**Comment by allisonletts** [comment]
Theoretically some of the detail from #102 could be moved out into the main UI, Run SQL - Drop Existing or Run SQL - Create New Only

**Comment by acrosman** [comment]
Related to #107, which also overhauls this step.

**Comment by acrosman** [comment]
PR #120 updates to labels on the elements mentioned to be clearer. Adding a button to preview the SQL is an interesting idea, but runs into a few issues:

1. That just a lot of SQL to see at once without a proper editor.  So then it would either need to be copy/pasted to an editor or at least formatting and colorizing needs to happen here.
2. KnexJS is handling several different SQL dialects internally, and doesn't make it easy to generate the statements until after a connection has been made – which is why the tool currently only allows for saving after it has been run.
3. The process is already self-healing on a couple details, most notably when the rows get too big it swaps data-types on text fields to make them play more nicely. Getting that reflected in the preview is another layer to the challenge.

I am leaving this open for future thoughts and ideas.  Others are welcome to offer PRs to take this further.
