### ISSUE TITLE
Error Creating Database - All Tables Failed

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#162]
**Describe the bug**
Basically every table was created (with errors, but created), showing all failed

**To Reproduce**
Long schema, sent via email.

**Expected behavior**
Tables complete with errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/17914696/169095618-56edb248-dab0-4031-a440-98800fc636fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Target Database: MariaDB

**Additional context**

**Comment by acrosman** [comment]
It appears this is triggered because something has changed about adding indexes, and there are two attempts. The second attempt fails with an error (as it should) and that error gets  reported as complete failure.

Two things should be adjusted: 
1. Since Knex adds indexes in a table alter statement after the table has been created, we should try to report to the user which phase has failed.
2. Creating Indexes should only be attempted once.
