### ISSUE TITLE
Data quirks

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#55]
**Describe the bug**
Some issues with data structures that have come up in practice:

 - Salesforce checkboxes come over as Bit(3) - expected Bit(1)
 - Enum should be changed to String--Talend is not super happy with Enum
 - Default values...maybe just shouldn't be set? Is that okay? The nulls are causing more problems than they're solving for me.

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Standard
 - Target Database: MariaDB

**Comment by acrosman** [comment]
For the checkboxes, they are actually set as `boolean` fields, which means the Knex library and the database engine select the bit count. It is mostly beyond the control of this tool and _shouldn't_ matter to other systems. I'd be interested to see counter examples where this caused a problem in practice.

Enum to String should be handled as part of #30 (I actually have a list of things for that I keep meaning to copy out of a notebook into the issue). Talend handles a few database types really poorly, ENUM it likes to make an object instead of a String.  Binary fields it likes to make a bit instead of a byte array, and a few other "interesting" choices crop up.  Figuring out how many of the bugs in a specific tool should get special handling is a challenge.  The settings proposed in #30 are meant to make that easier to address.  Also the balance on this of helping support validation of restricted picklists vs unrestricted is an open question here as well.

Default _aren't_ being set which is why it sets null (again that's default behavior of a combination of the library and/or database engine). It might be easier to set them for some use cases (assuming they are reasonably extractable from the metadata which it think is true but haven't double checked).  The Allow Null setting, which should also be default enabled, should make many uses not struggle with it.

**Comment by acrosman** [comment]
See proposed interface for option in #56

**Comment by acrosman** [comment]
Closed by #56
